#module declaration
module Neutrons
    #neutrons function
    def Neutrons.neutrons(element)
        #case statement that returns the amount of neutrons for the element
        case element.downcase
        when "hydrogen"
            return 0
        when "helium"
            return 2
        when "lithium"
            return 4
        when "beryllium"
            return 5
        when "boron"
            return 6
        when "carbon"
            return 6
        when "nitrogen"
            return 7
        when "oxygen"
            return 8
        when "fluorine"
            return 10
        when "neon"
            return 10
        when "sodium"
            return 12
        when "magnesium"
            return 12
        when "aluminium"
            return 14
        when "silicon"
            return 14
        when "phosphorus"
            return 16
        when "sulfur"
            return 16
        when "chlorine"
            return 18
        when "argon"
            return 22
        when "potassium"
            return 20
        when "calcium"
            return 20
        when "scandium"
            return 24
        when "titanium"
            return 22
        when "vanadium"
            return 28
        when "chromium"
            return 28
        when "manganese"
            return 30
        when "iron"
            return 30
        when "cobalt"
            return 32
        when "nickel"
            return 31
        when "copper"
            return 35
        when "zinc"
            return 30
        when "gallium"
            return 39
        when "germanium"
            return 41
        when "arsenic"
            return 42
        when "selenium"
            return 45
        when "bromine"
            return 45
        when "krypton"
            return 48
        when "rubidium"
            return 48
        when "strontium"
            return 50
        when "yttrium"
            return 50
        when "zirconium"
            return 51
        when "niobium"
            return 52
        when "molybdenum"
            return 54
        when "technetium"
            return 55
        when "ruthenium"
            return 57
        when "rhodium"
            return 58
        when "palladium"
            return 60
        when "silver"
            return 61
        when "cadmium"
            return 64
        when "indium"
            return 66
        when "tin"
            return 69
        when "antimony"
            return 71
        when "tellurium"
            return 76
        when "iodine"
            return 74
        #TODO: finish the rest of the elements
        #handler if the element provided is not valid
        else
            return "Invalid Element!"
        end
    end
end