#module declaration
module Protons
    #protons function
    def Protons.protons(element)
        #case statement that returns the amount of protons for the element
        case element.downcase
        when "hydrogen"
            return 1
        when "helium"
            return 2
        when "lithium"
            return 3
        when "beryllium"
            return 4
        when "boron"
            return 5
        when "carbon"
            return 6
        when "nitrogen"
            return 7
        when "oxygen"
            return 8
        when "fluorine"
            return 9
        when "neon"
            return 10
        when "sodium"
            return 11
        when "magnesium"
            return 12
        when "aluminium"
            return 13
        when "silicon"
            return 14
        when "phosphorus"
            return 15
        when "sulfur"
            return 16
        when "chlorine"
            return 17
        when "argon"
            return 18
        when "potassium"
            return 19
        when "calcium"
            return 20
        when "scandium"
            return 21
        when "titanium"
            return 22
        when "vanadium"
            return 23
        when "chromium"
            return 24
        when "manganese"
            return 25
        when "iron"
            return 26
        when "cobalt"
            return 27
        when "nickel"
            return 28
        when "copper"
            return 29
        when "zinc"
            return 30
        when "gallium"
            return 31
        when "germanium"
            return 32
        when "arsenic"
            return 33
        when "selenium"
            return 34
        when "bromine"
            return 35
        when "krypton"
            return 36
        when "rubidium"
            return 37
        when "strontium"
            return 38
        when "yttrium"
            return 39
        when "zirconium"
            return 40
        when "niobium"
            return 41
        when "molybdenum"
            return 42
        when "technetium"
            return 43
        when "ruthenium"
            return 44
        when "rhodium"
            return 45
        when "palladium"
            return 46
        when "silver"
            return 47
        when "cadmium"
            return 48
        when "indium"
            return 49
        when "tin"
            return 50
        when "antimony"
            return 51
        when "tellurium"
            return 52
        when "iodine"
            return 53
        when "xenon"
            return 54
        when "cesium"
            return 55
        when "barium"
            return 56
        when "lanthanum"
            return 57
        when "cerium"
            return 58
        when "praseodymium"
            return 59
        when "neodymium"
            return 60
        when "promethium"
            return 61
        when "samarium"
            return 62
        when "europium"
            return 63
        when "gadolinium"
            return 64
        when "terbium"
            return 65
        when "dysprosium"
            return 66
        when "holmium"
            return 67
        when "erbium"
            return 68
        when "thulium"
            return 69
        when "ytterbium"
            return 70
        when "lutetium"
            return 71
        when "hafnium"
            return 72
        when "tantalum"
            return 73
        when "tungsten"
            return 74
        when "rhenium"
            return 75
        when "osmium"
            return 76
        when "iridium"
            return 77
        when "platinum"
            return 78
        when "gold"
            return 79
        when "mercury"
            return 80
        when "thallium"
            return 81
        when "lead"
            return 82
        when "bismuth"
            return 83
        when "polonium"
            return 84
        when "astatine"
            return 85
        when "radon"
            return 86
        when "francium"
            return 87
        when "radium"
            return 88
        when "actinium"
            return 89
        when "thorium"
            return 90
        when "protactinium"
            return 91
        when "uranium"
            return 92
        when "neptunium"
            return 93
        when "plutonium"
            return 94
        when "americium"
            return 95
        when "curium"
            return 96
        when "berkelium"
            return 97
        when "californium"
            return 98
        when "einsteinium"
            return 99
        when "fermium"
            return 100
        when "mendelevium"
            return 101
        when "nobelium"
            return 102
        when "lawrencium"
            return 103
        when "rutherfordium"
            return 104
        when "dubnium"
            return 105
        when "seaborgium"
            return 106
        when "bohrium"
            return 107
        when "hassium"
            return 108
        when "meitnerium"
            return 109
        when "darmstadtium"
            return 110
        when "roentgenium"
            return 111
        when "copernicium"
            return 112
        when "nihonium"
            return 113
        when "flerovium"
            return 114
        when "moscovium"
            return 115
        when "livermorium"
            return 116
        when "tennessine"
            return 117
        when "oganesson"
            return 118
        else
            return "Invalid Element!"
        end
    end
end